//
// Created by axelzucho on 12/03/20.
//

#ifndef NFA_TO_DFA_SPECIALCHARACTERS_H
#define NFA_TO_DFA_SPECIALCHARACTERS_H

#define EPSILON 20
#define CONCAT_OP 19

#endif //NFA_TO_DFA_SPECIALCHARACTERS_H
